import type { Metadata } from 'next';
import '@/app/styles/globals.css';
import './globals.css';

export const metadata: Metadata = {
  title: '小罗的小世界',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='zh-CN'>
      <body className='antialiased'>{children}</body>
    </html>
  );
}
