import type { Metadata } from 'next';
import '@/app/styles/globals.css';
import './globals.css';
import GlobalNav from '@/components/layout/GlobalNav';

export const metadata: Metadata = {
  title: '小罗的小世界',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='zh-CN'>
      <body className='antialiased'>
        {children}
        <GlobalNav />
      </body>
    </html>
  );
}
